title: Ken B Morales
author: Ken B Morales
email: kbmorales@protonmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Ken B Morales CV.
show_excerpts: true # set to true to show excerpts on the homepage
markdown: kramdown

remote_theme: daattali/beautiful-jekyll

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  # parse markdown inside block-level HTML tag
  parse_block_html: true
